# .github/workflows/release.yaml

on:
  push:
  workflow_dispatch:

name: Build Release
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["386", "amd64", "arm", "arm64"]
        os: ["linux", "windows", "darwin", "android"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
      - name: compile and release
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
        run: |
          go build -ldflags '-w -s' -o gdrive-${{ matrix.os }}-${{ matrix.arch }}
      - name: upload release
        uses: actions/upload-artifact@v2
        with:
          name: gdrive-${{ matrix.os }}-${{ matrix.arch }}
          path: gdrive-${{ matrix.os }}-${{ matrix.arch }}
