# .github/workflows/release.yaml

on:
  release:
  workflow_dispatch:

name: Build Release
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["386", "amd64", "arm", "arm64"]
        os: ["linux", "windows", "darwin", "android"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
      - name: compile and release
        uses: ngs/go-release.action@v1.0.2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
          EXTRA_FILES: "LICENSE"
  # release-linux-386:
  #   name: release linux/386
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: compile and release
  #       uses: ngs/go-release.action@v1.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GOARCH: "386"
  #         GOOS: linux
  #         EXTRA_FILES: "LICENSE"
  # release-linux-amd64:
  #   name: release linux/amd64
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: compile and release
  #       uses: ngs/go-release.action@v1.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GOARCH: amd64
  #         GOOS: linux
  #         EXTRA_FILES: "LICENSE"
  # release-linux-arm:
  #   name: release linux/386
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: compile and release
  #       uses: ngs/go-release.action@v1.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GOARCH: "arm"
  #         GOOS: linux
  #         EXTRA_FILES: "LICENSE"
  # release-linux-arm64:
  #   name: release linux/amd64
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: compile and release
  #       uses: ngs/go-release.action@v1.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GOARCH: arm64
  #         GOOS: linux
  #         EXTRA_FILES: "LICENSE"
  # release-darwin-amd64:
  #   name: release darwin/amd64
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: compile and release
  #       uses: ngs/go-release.action@v1.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GOARCH: amd64
  #         GOOS: darwin
  #         EXTRA_FILES: "LICENSE"
  # release-windows-386:
  #   name: release windows/386
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: compile and release
  #       uses: ngs/go-release.action@v1.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GOARCH: "386"
  #         GOOS: windows
  #         EXTRA_FILES: "LICENSE"
  # release-windows-amd64:
  #   name: release windows/amd64
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: compile and release
  #       uses: ngs/go-release.action@v1.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GOARCH: amd64
  #         GOOS: windows
  #         EXTRA_FILES: "LICENSE"
